# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SRPUSH_Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRPushDemo
  pod 'Starscream', '~> 3.0.6'
  pod 'SwiftyJSON', '~> 4.2.0'
end
